### ISSUE TITLE
error: namespace 'xfun' 0.15 is being loaded, >=0.19 is required

### ISSUE THREAD

**Issue by jameslamb** [conda-forge/r-lintr-feedstock#12] opened 2021-01-28 16:42 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

In LightGBM, we use `conda` to manage dependencies in CI environments. For a job that runs a mix of Python, C++, and R linters, we install them all together in one conda environment.

You can run the code below to reproduce the issue we faced today in CI builds (https://github.com/microsoft/LightGBM/issues/3873).

```shell
conda create -y --name lintr-test python=3.8

source activate lintr-test

conda install -q -y -n lintr-test \
    pycodestyle \
    pydocstyle \
    r-stringi

conda install -q -y -n lintr-test \
    -c conda-forge \
        libxml2 \
        "r-lintr>=2.0"

source activate lintr-test

touch whatever.R

Rscript -e "lintr('whatever.R')"
```

That code produces this error

> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘xfun’ 0.15 is being loaded, but >= 0.19 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted

I don't know for sure if this is a problem with the recipe for `r-lintr` or something further upstream, but my best guess is `r-lintr` because this error shows up when I run `lintr::lint()`.

I was able to get around this by explicitly running `conda install -y "r-xfun>=0.19"`, but I wanted to report this because I do think some recipe (either this one of one of `r-lintr`'s dependencies) is missing that version floor on `xfun`.

Thanks for your time and consideration.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/jlamb/miniconda3/envs/lintr-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_r-mutex                  1.0.0               anacondar_1  
binutils_impl_linux-64    2.33.1               he6710b0_7  
binutils_linux-64         2.33.1              h9595d00_15  
bwidget                   1.9.11                        1  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.14.12              h8948797_3  
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
curl                      7.69.1               hbc83047_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
fribidi                   1.0.10               h7b6447c_0  
gcc_impl_linux-64         7.3.0                habb00fd_1  
gcc_linux-64              7.3.0               h553295d_15  
gfortran_impl_linux-64    7.3.0                hdf63c60_1  
gfortran_linux-64         7.3.0               h553295d_15  
glib                      2.66.1               h92f7085_0  
graphite2                 1.3.14               h23475e2_0  
gsl                       2.4                  h14c3975_4  
gxx_impl_linux-64         7.3.0                hdf63c60_1  
gxx_linux-64              7.3.0               h553295d_15  
harfbuzz                  2.4.0                hca77d97_1  
icu                       58.2                 he6710b0_3  
jpeg                      9b                   h024ee3a_2  
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.69.1               h20c2e04_0  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.3                h2531618_0  
make                      4.2.1                h1bed415_1  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1i               h27cfd23_0  
pango                     1.45.3               hd140c19_0  
pcre                      8.44                 he6710b0_0  
pip                       20.3.3           py38h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
pycodestyle               2.6.0                      py_0  
pydocstyle                5.1.1                      py_0  
python                    3.8.5                h7579374_1  
python_abi                3.8                      1_cp38    conda-forge
r-askpass                 1.1               r36hcdcec82_2    conda-forge
r-assertthat              0.2.1             r36h6115d3f_2    conda-forge
r-backports               1.1.4             r36h96ca727_0  
r-base                    3.6.1                haffb61f_2  
r-callr                   3.2.0             r36h6115d3f_0  
r-cli                     1.1.0             r36h6115d3f_0  
r-codetools               0.2_18            r36hc72bb7e_0    conda-forge
r-crayon                  1.3.4           r36h6115d3f_1003    conda-forge
r-curl                    4.3               r36hcdcec82_1    conda-forge
r-cyclocomp               1.1.0           r36h6115d3f_1004    conda-forge
r-desc                    1.2.0           r36h6115d3f_1003    conda-forge
r-digest                  0.6.27            r36h1b71b39_0    conda-forge
r-evaluate                0.14              r36h6115d3f_2    conda-forge
r-glue                    1.4.2             r36hcdcec82_0    conda-forge
r-highr                   0.8               r36h6115d3f_2    conda-forge
r-httr                    1.4.2             r36h6115d3f_0    conda-forge
r-jsonlite                1.6               r36h96ca727_0  
r-knitr                   1.31              r36hc72bb7e_0    conda-forge
r-lazyeval                0.2.2             r36hcdcec82_2    conda-forge
r-lintr                   2.0.1             r36h6115d3f_1    conda-forge
r-magrittr                2.0.1             r36h9e2df91_1    conda-forge
r-markdown                1.1               r36hcdcec82_1    conda-forge
r-mime                    0.9               r36hcdcec82_1    conda-forge
r-openssl                 1.4.3             r36he5c4762_0    conda-forge
r-praise                  1.0.0           r36h6115d3f_1004    conda-forge
r-processx                3.3.0             r36h96ca727_0  
r-ps                      1.3.0             r36h96ca727_0  
r-r6                      2.5.0             r36hc72bb7e_0    conda-forge
r-rcpp                    1.0.1             r36h29659fb_0  
r-remotes                 2.2.0             r36h6115d3f_0    conda-forge
r-rex                     1.2.0             r36h6115d3f_1    conda-forge
r-rlang                   0.3.4             r36h96ca727_0  
r-rprojroot               2.0.2             r36hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r36hc72bb7e_0    conda-forge
r-stringdist              0.9.6.3           r36h0eb13af_0    conda-forge
r-stringi                 1.4.3             r36h29659fb_0  
r-stringr                 1.4.0             r36h6115d3f_2    conda-forge
r-sys                     3.4               r36hcdcec82_0    conda-forge
r-testthat                2.1.1             r36h29659fb_0  
r-withr                   2.4.1             r36hc72bb7e_0    conda-forge
r-xfun                    0.15              r36h6115d3f_0    conda-forge
r-xml2                    1.3.2             r36h0357c0b_1    conda-forge
r-xmlparsedata            1.0.4             r36h6115d3f_0    conda-forge
r-yaml                    2.2.1             r36hcdcec82_1    conda-forge
readline                  8.0                  h7b6447c_0  
setuptools                52.0.0           py38h06a4308_0  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tktable                   2.10                 h14c3975_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

I'm on Ubuntu 18.04.

```
$ conda info
     active environment : lintr-test
    active env location : /home/jlamb/miniconda3/envs/lintr-test
            shell level : 1
       user config file : /home/jlamb/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/jlamb/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jlamb/miniconda3/pkgs
                          /home/jlamb/.conda/pkgs
       envs directories : /home/jlamb/miniconda3/envs
                          /home/jlamb/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.22.0 CPython/3.7.6 Linux/5.4.0-62-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by mfansler** [comment] 2023-06-15 14:23
Thanks for reporting this! I identified the root cause of this: https://github.com/conda-forge/r-knitr-feedstock/issues/35. As `r-lintr` is only incidental, I am closing this. You are welcome to track the other issue. However, patching metadata on old builds is not a priority.

**Closed as completed by mfansler** 2023-06-15 14:23 UTC

**Comment by jameslamb** [comment] 2023-06-15 14:29
Hey sure, thanks for coming back and investigating this!
